version: "2.1"
services:
  activities-ms:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      activities-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I activities-ms:4000/activities-ms/resources/activities/ --fail"
      interval: 20s
      retries: 10

  activities-db:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: activities-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
